// GENERATED by scripts/build-registry.mjs — do not edit.
// Run: npm run registry:build

export const REGISTRY_HOST = "https://lumenridge.github.io/ambientui"
export const INSTALLABLE_COMPONENTS = 31
export const REGISTRY_ITEMS = 36
