"use client"

import * as React from "react"

import {
  IconLibraryContext,
  type IconName,
} from "@ambientui/ui/lib/icon-library"

import {
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  Calendar01Icon,
  Alert02Icon,
  ArrowUp01Icon,
  ArrowUpRight01Icon,
  Attachment01Icon,
  Cancel01Icon,
  CodeIcon,
  Copy01Icon,
  Edit02Icon,
  FavouriteIcon,
  File01Icon,
  GlobalIcon,
  Image01Icon,
  Layers01Icon,
  SlidersHorizontalIcon,
  HistoryIcon,
  Link01Icon,
  MoreHorizontalIcon,
  PaintBoardIcon,
  Moon02Icon,
  PauseIcon,
  PlayIcon,
  PlusSignIcon,
  QuoteDownIcon,
  ReplayIcon,
  RulerIcon,
  ScissorIcon,
  Search01Icon,
  Settings01Icon,
  SidebarLeftIcon,
  Menu01Icon,
  Home01Icon,
  SmileIcon,
  StopIcon,
  SparklesIcon,
  Sun03Icon,
  TextFontIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  Tick02Icon,
  UserIcon,
} from "@hugeicons/core-free-icons"
import { HugeiconsIcon } from "@hugeicons/react"
import {
  IconCalendar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconAlertCircle,
  IconArrowUp,
  IconArrowUpRight,
  IconCode,
  IconCopy,
  IconDots,
  IconFileText,
  IconHeart,
  IconLayoutSidebar,
  IconMenu2,
  IconHome,
  IconLink,
  IconMoon,
  IconPalette,
  IconPaperclip,
  IconPencil,
  IconPhoto,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlus,
  IconQuote,
  IconReload,
  IconRuler2,
  IconScissors,
  IconSearch,
  IconSettings,
  IconMoodSmile,
  IconPlayerStop,
  IconSparkles,
  IconStack2,
  IconAdjustmentsHorizontal,
  IconHistory,
  IconSun,
  IconThumbDown,
  IconThumbUp,
  IconTypography,
  IconUser,
  IconWorld,
  IconX,
} from "@tabler/icons-react"
import {
  ArrowCounterClockwise,
  CalendarBlank,
  CaretDown,
  CaretLeft,
  CaretRight,
  Check,
  Code,
  Copy,
  DotsThree,
  FileText,
  Gear,
  Globe,
  Heart,
  MagnifyingGlass,
  Moon,
  Palette,
  Paperclip,
  Pause,
  PencilSimple,
  Play,
  Plus,
  ArrowUp as PhArrowUp,
  ArrowUpRight as PhArrowUpRight,
  Image as PhImage,
  Link as PhLink,
  Quotes,
  Ruler,
  Scissors,
  Sidebar as PhSidebar,
  List as PhList,
  House as PhHouse,
  Smiley,
  Stack,
  SlidersHorizontal as PSliders,
  ClockCounterClockwise,
  Stop,
  ThumbsDown,
  ThumbsUp,
  TextT,
  WarningCircle,
  Sparkle,
  Sun,
  User,
  X,
} from "@phosphor-icons/react"
import {
  RiAddLine,
  RiArrowDownSLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiArrowUpLine,
  RiArrowRightUpLine,
  RiAttachment2,
  RiCalendarLine,
  RiCodeSSlashLine,
  RiDoubleQuotesL,
  RiErrorWarningLine,
  RiFileCopyLine,
  RiFileTextLine,
  RiGlobalLine,
  RiImageLine,
  RiLinkM,
  RiMoreFill,
  RiPaletteLine,
  RiPencilLine,
  RiRulerLine,
  RiScissorsLine,
  RiEmotionLine,
  RiText,
  RiStopLine,
  RiStackLine,
  RiEqualizerLine,
  RiHistoryLine,
  RiThumbDownLine,
  RiThumbUpLine,
  RiCheckLine,
  RiCloseLine,
  RiHeartLine,
  RiLayoutLeftLine,
  RiMenuLine,
  RiHomeLine,
  RiMoonLine,
  RiPauseLine,
  RiPlayLine,
  RiRestartLine,
  RiSearchLine,
  RiSettings3Line,
  RiSparklingLine,
  RiSunLine,
  RiUserLine,
} from "@remixicon/react"
import {
  Calendar as LCalendar,
  Check as LCheck,
  Code as LCode,
  ChevronDown as LChevronDown,
  ArrowUp as LArrowUp,
  ArrowUpRight as LArrowUpRight,
  ChevronLeft as LChevronLeft,
  CircleAlert as LCircleAlert,
  Copy as LCopy,
  Image as LImage,
  MoreHorizontal as LMoreHorizontal,
  Paperclip as LPaperclip,
  Pencil as LPencil,
  Quote as LQuote,
  Scissors as LScissors,
  Layers as LLayers,
  SlidersHorizontal as LSliders,
  History as LHistory,
  Palette as LPalette,
  Ruler as LRuler,
  Smile as LSmile,
  Square as LSquare,
  Type as LType,
  ThumbsDown as LThumbsDown,
  ThumbsUp as LThumbsUp,
  FileText as LFileText,
  Globe as LGlobe,
  Link as LLink,
  ChevronRight as LChevronRight,
  Heart as LHeart,
  Moon as LMoon,
  PanelLeft as LPanelLeft,
  Menu as LMenu,
  House as LHouse,
  Pause as LPause,
  Play as LPlay,
  Plus as LPlus,
  RotateCcw as LRotateCcw,
  Search as LSearch,
  Settings as LSettings,
  Sparkles as LSparkles,
  Sun as LSun,
  User as LUser,
  X as LX,
} from "lucide-react"

/**
 * The system's icon component. Components name icons SEMANTICALLY; the
 * Foundation's icon-library choice — supplied through IconLibraryProvider —
 * decides which set draws them. The same governance shape as colors and
 * spacing: select the library once, everything follows. New names must be
 * mapped in every library or they don't exist.
 */


type Renderer = (size: number, strokeWidth: number, className?: string) => React.ReactNode

const hi =
  (icon: typeof SparklesIcon): Renderer =>
  (size, strokeWidth, className) => (
    <HugeiconsIcon icon={icon} size={size} strokeWidth={strokeWidth} className={className} />
  )
const lu =
  (C: React.ComponentType<{ size?: number; strokeWidth?: number; className?: string }>): Renderer =>
  (size, strokeWidth, className) => <C size={size} strokeWidth={strokeWidth} className={className} />
const tb = lu
const ph =
  (C: React.ComponentType<{ size?: number; className?: string }>): Renderer =>
  (size, _sw, className) => <C size={size} className={className} />
const rx =
  (
    C: React.ComponentType<{ size?: number | string; className?: string }>
  ): Renderer =>
  (size, _sw, className) => <C size={size} className={className} />

const SETS: Record<string, Record<IconName, Renderer>> = {
  hugeicons: {
    search: hi(Search01Icon),
    settings: hi(Settings01Icon),
    user: hi(UserIcon),
    heart: hi(FavouriteIcon),
    check: hi(Tick02Icon),
    close: hi(Cancel01Icon),
    "chevron-down": hi(ArrowDown01Icon),
    "chevron-left": hi(ArrowLeft01Icon),
    "chevron-right": hi(ArrowRight01Icon),
    sidebar: hi(SidebarLeftIcon),
    menu: hi(Menu01Icon),
    home: hi(Home01Icon),
    sun: hi(Sun03Icon),
    moon: hi(Moon02Icon),
    play: hi(PlayIcon),
    pause: hi(PauseIcon),
    replay: hi(ReplayIcon),
    sparkles: hi(SparklesIcon),
    plus: hi(PlusSignIcon),
    calendar: hi(Calendar01Icon),
    document: hi(File01Icon),
    link: hi(Link01Icon),
    globe: hi(GlobalIcon),
    code: hi(CodeIcon),
    "copy": hi(Copy01Icon),
    "paperclip": hi(Attachment01Icon),
    "image": hi(Image01Icon),
    "arrow-up": hi(ArrowUp01Icon),
    "arrow-up-right": hi(ArrowUpRight01Icon),
    "alert": hi(Alert02Icon),
    "edit": hi(Edit02Icon),
    "quote": hi(QuoteDownIcon),
    "scissors": hi(ScissorIcon),
    "type": hi(TextFontIcon),
    "smile": hi(SmileIcon),
    "stop": hi(StopIcon),
    "palette": hi(PaintBoardIcon),
    "ruler": hi(RulerIcon),
    "layers": hi(Layers01Icon),
    "sliders": hi(SlidersHorizontalIcon),
    "history": hi(HistoryIcon),
    "more": hi(MoreHorizontalIcon),
    "thumbs-down": hi(ThumbsDownIcon),
    "thumbs-up": hi(ThumbsUpIcon),
  },
  lucide: {
    search: lu(LSearch),
    settings: lu(LSettings),
    user: lu(LUser),
    heart: lu(LHeart),
    check: lu(LCheck),
    close: lu(LX),
    "chevron-down": lu(LChevronDown),
    "chevron-left": lu(LChevronLeft),
    "chevron-right": lu(LChevronRight),
    sidebar: lu(LPanelLeft),
    menu: lu(LMenu),
    home: lu(LHouse),
    sun: lu(LSun),
    moon: lu(LMoon),
    play: lu(LPlay),
    pause: lu(LPause),
    replay: lu(LRotateCcw),
    sparkles: lu(LSparkles),
    plus: lu(LPlus),
    calendar: lu(LCalendar),
    document: lu(LFileText),
    link: lu(LLink),
    globe: lu(LGlobe),
    code: lu(LCode),
    "copy": lu(LCopy),
    "paperclip": lu(LPaperclip),
    "image": lu(LImage),
    "arrow-up": lu(LArrowUp),
    "arrow-up-right": lu(LArrowUpRight),
    "alert": lu(LCircleAlert),
    "edit": lu(LPencil),
    "quote": lu(LQuote),
    "scissors": lu(LScissors),
    "type": lu(LType),
    "smile": lu(LSmile),
    "stop": lu(LSquare),
    "palette": lu(LPalette),
    "ruler": lu(LRuler),
    "layers": lu(LLayers),
    "sliders": lu(LSliders),
    "history": lu(LHistory),
    "more": lu(LMoreHorizontal),
    "thumbs-down": lu(LThumbsDown),
    "thumbs-up": lu(LThumbsUp),
  },
  tabler: {
    search: tb(IconSearch),
    settings: tb(IconSettings),
    user: tb(IconUser),
    heart: tb(IconHeart),
    check: tb(IconCheck),
    close: tb(IconX),
    "chevron-down": tb(IconChevronDown),
    "chevron-left": tb(IconChevronLeft),
    "chevron-right": tb(IconChevronRight),
    sidebar: tb(IconLayoutSidebar),
    menu: tb(IconMenu2),
    home: tb(IconHome),
    sun: tb(IconSun),
    moon: tb(IconMoon),
    play: tb(IconPlayerPlay),
    pause: tb(IconPlayerPause),
    replay: tb(IconReload),
    sparkles: tb(IconSparkles),
    plus: tb(IconPlus),
    calendar: tb(IconCalendar),
    document: tb(IconFileText),
    link: tb(IconLink),
    globe: tb(IconWorld),
    code: tb(IconCode),
    "copy": tb(IconCopy),
    "paperclip": tb(IconPaperclip),
    "image": tb(IconPhoto),
    "arrow-up": tb(IconArrowUp),
    "arrow-up-right": tb(IconArrowUpRight),
    "alert": tb(IconAlertCircle),
    "edit": tb(IconPencil),
    "quote": tb(IconQuote),
    "scissors": tb(IconScissors),
    "type": tb(IconTypography),
    "smile": tb(IconMoodSmile),
    "stop": tb(IconPlayerStop),
    "palette": tb(IconPalette),
    "ruler": tb(IconRuler2),
    "layers": tb(IconStack2),
    "sliders": tb(IconAdjustmentsHorizontal),
    "history": tb(IconHistory),
    "more": tb(IconDots),
    "thumbs-down": tb(IconThumbDown),
    "thumbs-up": tb(IconThumbUp),
  },
  phosphor: {
    search: ph(MagnifyingGlass),
    settings: ph(Gear),
    user: ph(User),
    heart: ph(Heart),
    check: ph(Check),
    close: ph(X),
    "chevron-down": ph(CaretDown),
    "chevron-left": ph(CaretLeft),
    "chevron-right": ph(CaretRight),
    sidebar: ph(PhSidebar),
    menu: ph(PhList),
    home: ph(PhHouse),
    sun: ph(Sun),
    moon: ph(Moon),
    play: ph(Play),
    pause: ph(Pause),
    replay: ph(ArrowCounterClockwise),
    sparkles: ph(Sparkle),
    plus: ph(Plus),
    calendar: ph(CalendarBlank),
    document: ph(FileText),
    link: ph(PhLink),
    globe: ph(Globe),
    code: ph(Code),
    "copy": ph(Copy),
    "paperclip": ph(Paperclip),
    "image": ph(PhImage),
    "arrow-up": ph(PhArrowUp),
    "arrow-up-right": ph(PhArrowUpRight),
    "alert": ph(WarningCircle),
    "edit": ph(PencilSimple),
    "quote": ph(Quotes),
    "scissors": ph(Scissors),
    "type": ph(TextT),
    "smile": ph(Smiley),
    "stop": ph(Stop),
    "palette": ph(Palette),
    "ruler": ph(Ruler),
    "layers": ph(Stack),
    "sliders": ph(PSliders),
    "history": ph(ClockCounterClockwise),
    "more": ph(DotsThree),
    "thumbs-down": ph(ThumbsDown),
    "thumbs-up": ph(ThumbsUp),
  },
  remix: {
    search: rx(RiSearchLine),
    settings: rx(RiSettings3Line),
    user: rx(RiUserLine),
    heart: rx(RiHeartLine),
    check: rx(RiCheckLine),
    close: rx(RiCloseLine),
    "chevron-down": rx(RiArrowDownSLine),
    "chevron-left": rx(RiArrowLeftSLine),
    "chevron-right": rx(RiArrowRightSLine),
    sidebar: rx(RiLayoutLeftLine),
    menu: rx(RiMenuLine),
    home: rx(RiHomeLine),
    sun: rx(RiSunLine),
    moon: rx(RiMoonLine),
    play: rx(RiPlayLine),
    pause: rx(RiPauseLine),
    replay: rx(RiRestartLine),
    sparkles: rx(RiSparklingLine),
    plus: rx(RiAddLine),
    calendar: rx(RiCalendarLine),
    document: rx(RiFileTextLine),
    link: rx(RiLinkM),
    globe: rx(RiGlobalLine),
    code: rx(RiCodeSSlashLine),
    "copy": rx(RiFileCopyLine),
    "paperclip": rx(RiAttachment2),
    "image": rx(RiImageLine),
    "arrow-up": rx(RiArrowUpLine),
    "arrow-up-right": rx(RiArrowRightUpLine),
    "alert": rx(RiErrorWarningLine),
    "edit": rx(RiPencilLine),
    "quote": rx(RiDoubleQuotesL),
    "scissors": rx(RiScissorsLine),
    "type": rx(RiText),
    "smile": rx(RiEmotionLine),
    "stop": rx(RiStopLine),
    "palette": rx(RiPaletteLine),
    "ruler": rx(RiRulerLine),
    "layers": rx(RiStackLine),
    "sliders": rx(RiEqualizerLine),
    "history": rx(RiHistoryLine),
    "more": rx(RiMoreFill),
    "thumbs-down": rx(RiThumbDownLine),
    "thumbs-up": rx(RiThumbUpLine),
  },
}


export function IconLibraryProvider({
  library,
  children,
}: {
  library: string
  children: React.ReactNode
}) {
  return (
    <IconLibraryContext.Provider value={library}>
      {children}
    </IconLibraryContext.Provider>
  )
}

export interface IconProps {
  name: IconName
  size?: number
  strokeWidth?: number
  className?: string
  /** Force a specific library (previews only — everything else follows the config). */
  library?: string
}

export function Icon({
  name,
  size = 16,
  strokeWidth = 1.8,
  className,
  library,
}: IconProps) {
  const configured = React.useContext(IconLibraryContext)
  const set = SETS[library ?? configured] ?? SETS.hugeicons!
  return <>{set[name](size, strokeWidth, className)}</>
}

export type { IconName }
