"use client"

import * as React from "react"

import { Button } from "@ambientui/ui/components/button"

import { CommandLine } from "@/components/command-line"
import { Icon } from "@ambientui/ui/components/icon"
import {
  INSTALLABLE_COMPONENTS,
  REGISTRY_HOST,
} from "@/lib/registry-facts"

/**
 * HOW SOMEONE TAKES THIS — the section the whole site exists to reach.
 *
 * Everything above it argues; this is where a visitor stops reading and
 * starts typing.
 *
 * TWO TRACKS, NOT FOUR TILES. The doors divide on a real line: the first
 * two give you things that RENDER, the last two give you the thing that
 * DECIDES what rendering looks like. Four peer tiles made a visitor
 * classify themselves before they knew what any of it was; two named
 * tracks tell them which half of the argument is theirs.
 *
 * The command block itself lives in components/command-line.tsx — composed,
 * not promoted (owner's call), but written once now that more than one
 * surface needs it.
 *
 * ONLY COMMANDS THAT RUN, and that rule is now MECHANICAL: every command
 * here is a door in scripts/verify-install.mjs, which installs it into a
 * scratch project that is not this repo, then typechecks and builds that
 * project. The Foundation door printed no command for weeks because
 * nothing had run it; it prints one now because something does.
 *
 * NOTHING HERE IS TYPED TWICE. The host and the component count come from
 * registry-facts.ts, generated by the registry build, because a landing
 * page that renders perfectly while handing out a dead URL is the worst
 * failure this section has.
 */

/** The one-off registry registration, so every later command can be short. */
const SETUP = `npx shadcn registry add @ambientui=${REGISTRY_HOST}/r/{name}.json`

type Door = {
  id: string
  label: string
  blurb: string
  command?: string
  icon: React.ComponentProps<typeof Icon>["name"]
}

const TRACKS: {
  id: string
  title: string
  lede: string
  doors: Door[]
}[] = [
  {
    id: "components",
    title: "Take the components",
    lede: "The parts you can see. They land in your repo as code you own.",
    doors: [
      {
        id: "layer",
        label: "The whole ambient layer",
        blurb:
          "Everything this page just showed you: the orb, the spotlight, the panel, the dock and the history, plus the wiring that lets a page tell it where you are.",
        command: "npx shadcn add @ambientui/ambient-layer",
        icon: "sparkles",
      },
      {
        id: "component",
        label: "One component",
        blurb: `Just the piece you need — the reasoning panel, the tool timeline, the diff. ${INSTALLABLE_COMPONENTS} to choose from, each documented with what it is and is not for.`,
        command: "npx shadcn add @ambientui/reasoning-panel",
        icon: "layers",
      },
    ],
  },
  {
    id: "architecture",
    title: "Adopt the architecture",
    lede: "The part that decides how everything looks.",
    doors: [
      {
        id: "foundation",
        label: "A design system to build inside",
        blurb:
          "The Foundation: the short menu of values everything else reads from — colour, grey, corners, spacing, type, motion. You can take this on its own, with no assistant attached.",
        command: "npx shadcn add @ambientui/foundation",
        icon: "sliders",
      },
      {
        id: "governance",
        label: "The rules your AI works under",
        blurb:
          "The rules your AI reads before it writes anything, and three reviewer roles it can take on. This is the part nobody else ships.",
        command: "npx shadcn add @ambientui/governance",
        icon: "document",
      },
    ],
  },
]

export function InstallSection({ onDocs }: { onDocs?: () => void }) {
  return (
    <section id="install" className="flex scroll-mt-24 flex-col gap-10">
      <div className="flex flex-col gap-4">
        <span className="text-muted-foreground font-mono text-xs tracking-widest uppercase">
          Take it
        </span>
        <h2 className="max-w-2xl text-4xl leading-tight font-semibold tracking-tight text-balance">
          The whole layer, in one command
        </h2>
        <p className="text-muted-foreground max-w-xl text-base leading-relaxed">
          The code lands in your repo, not in node_modules. You can open it
          and change it, because a system you cannot change is not really
          yours. It is built on shadcn/ui and Tailwind CSS, so it fits with
          what you already have.
        </p>
      </div>

      <div className="flex flex-col gap-3">
        <CommandLine
          size="lead"
          command="npx shadcn add @ambientui/ambient-layer"
        />
        <p className="text-muted-foreground text-sm leading-relaxed">
          Register the namespace once and every command stays short:
        </p>
        <CommandLine command={SETUP} />
      </div>

      {TRACKS.map((track) => (
        <div key={track.id} className="border-border border-t pt-10">
          <div className="mb-8 flex flex-col gap-1.5">
            <h3 className="text-lg font-semibold tracking-tight">
              {track.title}
            </h3>
            <p className="text-muted-foreground text-sm leading-relaxed">
              {track.lede}
            </p>
          </div>
          <div className="grid gap-x-12 gap-y-8 sm:grid-cols-2">
            {track.doors.map((d) => (
              <div key={d.id} className="flex flex-col gap-3">
                <div className="flex items-center gap-2.5">
                  <span className="text-muted-foreground">
                    <Icon name={d.icon} size={15} />
                  </span>
                  <h4 className="text-sm font-semibold">{d.label}</h4>
                </div>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  {d.blurb}
                </p>
                {d.command ? (
                  <CommandLine command={d.command} />
                ) : (
                  <Button
                    variant="outline"
                    className="self-start"
                    onClick={onDocs}
                  >
                    Read the Foundation
                    <Icon name="arrow-up-right" size={14} />
                  </Button>
                )}
              </div>
            ))}
          </div>
        </div>
      ))}
    </section>
  )
}
